// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARsBpBSgHkakOTlAbMT9y6QweTFFZMvtI',
    appId: '1:232998208665:web:043c37a2b19b54258f2408',
    messagingSenderId: '232998208665',
    projectId: 'crud-firebase-c8d06',
    authDomain: 'crud-firebase-c8d06.firebaseapp.com',
    storageBucket: 'crud-firebase-c8d06.appspot.com',
    measurementId: 'G-3RVD2FZDLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1g447uEuHLvNQNa0oHAg8Ffkz2X6ulc0',
    appId: '1:232998208665:android:47ee7a15bd6741ec8f2408',
    messagingSenderId: '232998208665',
    projectId: 'crud-firebase-c8d06',
    storageBucket: 'crud-firebase-c8d06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2FOKlCqvwrt8sgleRtF3X6RjhPWhuPNM',
    appId: '1:232998208665:ios:e423fd97ccfeb1398f2408',
    messagingSenderId: '232998208665',
    projectId: 'crud-firebase-c8d06',
    storageBucket: 'crud-firebase-c8d06.appspot.com',
    iosBundleId: 'com.example.crudfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2FOKlCqvwrt8sgleRtF3X6RjhPWhuPNM',
    appId: '1:232998208665:ios:e423fd97ccfeb1398f2408',
    messagingSenderId: '232998208665',
    projectId: 'crud-firebase-c8d06',
    storageBucket: 'crud-firebase-c8d06.appspot.com',
    iosBundleId: 'com.example.crudfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARsBpBSgHkakOTlAbMT9y6QweTFFZMvtI',
    appId: '1:232998208665:web:68f378ef6ada3dca8f2408',
    messagingSenderId: '232998208665',
    projectId: 'crud-firebase-c8d06',
    authDomain: 'crud-firebase-c8d06.firebaseapp.com',
    storageBucket: 'crud-firebase-c8d06.appspot.com',
    measurementId: 'G-Q6PN881PLN',
  );
}
